import React from "react";

export const translations = {
  0: {
    chooseLang: "Choose language",
    calm: "Calm",
    quietWind: "Quiet wind",
    lightBreeze: 'Light breeze',
    weakWind: 'Weak wind',
    moderateWind: 'Moderate wind',
    freshBreeze: 'Fresh breeze',
    strongWind: 'Strong wind',
    strongerWind: 'Stronger wind',
    veryStrongWind: 'Very strong wind',
    storm: 'Storm',
    heavyStorm: 'Heavy storm',
    cruelStorm: 'Cruel storm',
    hurricane: 'Hurricane',
    NNE: 'NNE',
    NE: 'NE',
    NEE: 'NEE',
    east: 'E',
    SEE: 'SEE',
    SE: 'SE',
    SSE: 'SSE',
    south: 'S',
    SSW: 'SSW',
    SW: 'SW',
    SWW: 'SWW',
    west: 'W',
    NWW: 'NWW',
    NW: 'NW',
    NNW: 'NNW',
    north: 'N'
  },
  1: {
    chooseLang: "Выберите язык",
    calm: "Штиль",
    quietWind: "Тихий ветер",
    lightBreeze: 'Лёгкий ветер',
    weakWind: 'Слабый ветер',
    moderateWind: 'Умеренный ветер',
    freshBreeze: 'Свежий ветер',
    strongWind: 'Сильный ветер',
    strongerWind: 'Крепкий ветер',
    veryStrongWind: 'Очень крепкий ветер',
    storm: 'Шторм',
    heavyStorm: 'Сильный шторм',
    cruelStorm: 'Жестокий шторм',
    hurricane: 'Ураган',
    NNE: 'ССВ',
    NE: 'СВ',
    NEE: 'ВВС',
    east: 'В',
    SEE: 'ВВЮ',
    SE: 'ЮВ',
    SSE: 'ЮЮВ',
    south: 'Ю',
    SSW: 'ЮЮЗ',
    SW: 'ЮЗ',
    SWW: 'ЗЗЮ',
    west: 'З',
    NWW: 'ЗЗС',
    NW: 'СЗ',
    NNW: 'ССЗ',
    north: 'С'
  },
};
export const TranslationContext = React.createContext(translations[0]);
